version: '3.8'
services:
  go-api-demo:
    container_name: go-api-demo
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports: 
      - '8080:8080'
    volumes:
      - ./src:/go/src/go_api_demo_service
